version: "3.9"  # Remove the version if it's causing issues, since it's deprecated

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: growthiq_app_container
    ports:
      - "8501:8501"  # Expose the Streamlit port
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      - PYTHONUNBUFFERED=1
    command: poetry run streamlit run growthiq/growth_dashboard.py
